### ISSUE TITLE
Implementar maquete de tela

### ISSUE THREAD

**Issue by feliperubin** [Felipe-Rubin/ScrumEngSoftware#4]
A maquete de tela deve ser implementada em Java

**Comment by JoaoMoraesJr** [comment]
Parte 1 da Maquete de Tela
[Maquete_de_tela.zip](https://github.com/Felipe-Rubin/ScrumEngSoftware/files/973279/Maquete_de_tela.zip)

**Comment by JoaoMoraesJr** [comment]
Parte 2 e 3 da Maquete de Tela (Não consigo passar para o código direto)
[ScrumEngSoftware-master.zip](https://github.com/Felipe-Rubin/ScrumEngSoftware/files/987814/ScrumEngSoftware-master.zip)
